version: "3"
services:
  app:
    container_name: "web_app"
    build: ./HackerNewsASW
    environment:
      - "PGUSER=root"
      - "PGHOST=pg"
      - "PGPASSWORD=root_password"
      - "PGDATABASE=db"
      - "PGPORT=5432"
    ports:
      - "80:80"
      - "443:443"
    #volumes: 
      #- ./app:/usr/src/app
    depends_on: 
      - "pg"
  pg:
    image: "postgres:12"
    container_name: "pgsql"
    environment:
      - "POSTGRES_PASSWORD=root_password"
      - "POSTGRES_USER=root"
      - "POSTGRES_DB=webapp"
    ports:
      - "5488:5432"
    volumes:
      - ./pg/db_data:/var/lib/postgresql/data
  angular:
    container_name: "angular_app"
    build: ./HackerNewsAngular
    ports:
      - "80:80"
    depends_on:
      - "app"